=== slemarchand/social-tops/social-tops-repo/config/alfresco/module/social_tops/definitions/topDefinitions_1_0.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema elementFormDefault="qualified" version="1.0" targetNamespace="http://slemarchand.github.org/social-tops/definitions/1.0" xmlns:tns="http://slemarchand.github.org/social-tops/definitions/1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="social-tops" type="tns:topDefinitions"/>

  <xs:complexType name="entitled" abstract="true">
    <xs:sequence>
      <xs:element name="title" type="xs:string" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="topCount">
    <xs:complexContent>
      <xs:extension base="tns:entitled">
        <xs:sequence/>
        <xs:attribute name="value" type="xs:int" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="topCriterion">
    <xs:sequence/>
    <xs:attribute name="activity" type="xs:string" use="required"/>
    <xs:attribute name="weight" type="xs:int" use="required"/>
  </xs:complexType>

  <xs:complexType name="topDefinitions">
    <xs:sequence>
      <xs:element name="counts">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="count" type="tns:topCount" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="types">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="type" type="tns:topType" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="ranges">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="range" type="tns:topRange" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="topType">
    <xs:complexContent>
      <xs:extension base="tns:entitled">
        <xs:sequence>
          <xs:element name="criterion" type="tns:topCriterion" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="topRange">
    <xs:complexContent>
      <xs:extension base="tns:entitled">
        <xs:sequence/>
        <xs:attribute name="days" type="xs:int" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
</xs:schema>

=== slemarchand/social-tops/social-tops-repo/config/alfresco/module/social_tops/definitions/topDefinitions.xml
<?xml version="1.0"?>
<social-tops xmlns="http://slemarchand.github.org/social-tops/definitions/1.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://slemarchand.github.org/social-tops/definitions/1.0 topDefinitions_1_0.xsd">

	<counts>
		<count value="5">
			<title>Top 5</title>
		</count>
		<count value="10">
			<title>Top 10</title>
		</count>
		<count value="10">
			<title>Top 20</title>
		</count>
	</counts>

	<types>
		<!-- TODO: remplir avec plein d'exemples parlants -->
		<type id="most-active-people">
			<title>most active people</title>
			<criterion activity="org.alfresco.documentlibrary.file-liked" weight="1" />
			<criterion activity="org.alfresco.comments.comment-created" weight="2" />
		</type>
		<type id="most-liking-people">
			<title>most liking people</title>
			<criterion activity="org.alfresco.documentlibrary.file-liked" weight="2" />
		</type>
		<type id="most-talkative-people">
			<title>most talkative people</title>
			<criterion activity="org.alfresco.documentlibrary.file-liked" weight="1" />
			<criterion activity="org.alfresco.comments.comment-created" weight="2" />
		</type>
	</types>

	<ranges>
		<range days="0">
			<title>today</title>
		</range>
		<range days="7">
			<title>in the last 7 days</title>
		</range>
		<range days="14">
			<title>in the last 14 days</title>
		</range>
		<range days="28">
			<title>in the last 28 days</title>
		</range>
		<range days="61">
			<title>in the last 2 months</title>
		</range>
		<range days="91">
			<title>in the last 3 months</title>
		</range>
		<range days="182">
			<title>in the last 6 months</title>
		</range>
	</ranges>

</social-tops>
